name: "Wibutler"
description: "Wibutler mqtt bridge"
version: "1.0.0"
slug: "wibutler"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
startup: services
services:
  - mqtt:need
options:
  wibutler_host:
  wibutler_username:
  wibutler_password:
schema:
  wibutler_host: str
  wibutler_username: str
  wibutler_password: password
